// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE

import * as MainElm from "../elm/Main.elm";

function init(prim) {
  return MainElm.Elm.Main.init(prim);
}

var newApp = MainElm.Elm.Main.init({
      node: document.getElementById("elm")
    });

var Ports = /* module */[];

export {
  init ,
  newApp ,
  Ports ,
  
}
/* newApp Not a pure module */
