// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE

import * as Curry from "../node_modules/bs-platform/lib/es6/curry.js";
import * as Elm$ReasonableRustyElm from "./Elm.bs.js";
import * as Psd$ReasonableRustyElm from "./Psd.bs.js";
import * as Render$ReasonableRustyElm from "./Render.bs.js";

Elm$ReasonableRustyElm.newApp.ports.hello.subscribe((function (param) {
        Psd$ReasonableRustyElm.hello(/* () */0);
        console.log("Calling this port from ReasonML");
        return /* () */0;
      }));

Elm$ReasonableRustyElm.newApp.ports.renderImage.subscribe((function (imageUrl) {
        var decodedString = atob(imageUrl.split(",")[1]);
        var arrayBuffer = new Uint8Array(decodedString.length);
        console.log(arrayBuffer);
        return Curry._2(Render$ReasonableRustyElm.renderPsd, imageUrl, "canvas");
      }));

export {
  
}
/*  Not a pure module */
