// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE

import * as MainElm from "../elm/Main.elm";
import * as Rusty_elm from "../crate/pkg/rusty_elm";

function hello(prim) {
  Rusty_elm.hello();
  return /* () */0;
}

function init(prim) {
  return MainElm.Elm.Main.init(prim);
}

var newApp = MainElm.Elm.Main.init({
      node: document.getElementById("elm")
    });

newApp.ports.hello.subscribe((function (param) {
        Rusty_elm.hello();
        console.log("Calling this port from ReasonML");
        return /* () */0;
      }));

export {
  hello ,
  init ,
  newApp ,
  
}
/* newApp Not a pure module */
