// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE

import * as Rusty_elm from "../crate/pkg/rusty_elm";

function renderPsd(prim) {
  return Rusty_elm.render_psd(prim);
}

export {
  renderPsd ,
  
}
/* ../crate/pkg/rusty_elm Not a pure module */
