// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE

import * as Rusty_elm from "../crate/pkg/rusty_elm";

function hello(prim) {
  Rusty_elm.hello();
  return /* () */0;
}

export {
  hello ,
  
}
/* ../crate/pkg/rusty_elm Not a pure module */
