// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE

import * as Rusty_elm from "../crate/pkg/rusty_elm";

function parsePsd(prim) {
  return Rusty_elm.parse_psd(prim);
}

export {
  parsePsd ,
  
}
/* ../crate/pkg/rusty_elm Not a pure module */
