// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE


var renderImageWithDataUrl = ((dataUrl, id) => {

    const canvas = document.getElementById(id);
    const ctx = canvas.getContext('2d');

    const img = new Image();
    img.src = dataUrl;
    img.onload = () => {
        ctx.drawImage(img, 0, 0);
    }
  });

var renderPsd = ((id, imageData) => {
        const canvas = document.getElementById(id);
        const ctx = canvas.getContext('2d');
        ctx.putImageData(imageData, 0, 0);
    });

var clearCanvas = ((id) => {
        const canvas = document.getElementById(id);
        const ctx = canvas.getContext('2d');
        ctx.clearRect(0, 0, canvas.width, canvas.height);
    });

var getActiveFile = ((id) => {
        const canvas = document.getElementById(id);
        return canvas.toDataURL();
    });

var decodeImage = ((dataUrl, cb) => {
        const image = new Image();
        image.src = dataUrl;

        const canvas = new OffscreenCanvas(image.width, image.height);
        const ctx = canvas.getContext('2d');

        image.decode()
            .then(() => {
                 ctx.drawImage(image, 0, 0);
                 const imageData = ctx.getImageData(0, 0, image.width, image.height);
                 cb(imageData);
            });
    });

export {
  renderImageWithDataUrl ,
  renderPsd ,
  clearCanvas ,
  getActiveFile ,
  decodeImage ,
  
}
/* renderImageWithDataUrl Not a pure module */
