// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE


var renderPsd = ((dataUrl, id) => {

    const canvas = document.getElementById(id);
    const ctx = canvas.getContext('2d');

    const img = new Image();
    img.src = dataUrl;

    img.onload = () => {
        ctx.drawImage(img, 0, 0);
    }
  });

export {
  renderPsd ,
  
}
/* renderPsd Not a pure module */
